# Generated by Django 3.2.8 on 2021-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('centerId', models.CharField(max_length=100)),
                ('typeId', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='facility_reservering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
                ('begin_time', models.IntegerField()),
                ('during', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='facility_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField()),
                ('facility', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ac_socket', models.IntegerField()),
                ('locker', models.IntegerField()),
                ('cabinet', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('projector', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='office_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerId', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('flat', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('building', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('planId', models.IntegerField(primary_key=True, serialize=False)),
                ('typeId', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'hour'), (1, 'day'), (2, 'month')])),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField(choices=[(0, 'walk-in'), (1, 'reservation')])),
            ],
        ),
    ]
