# Generated by Django 3.2.8 on 2021-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_facility_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_plan',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility_reservering',
            name='unit',
            field=models.IntegerField(choices=[(0, 'hour'), (1, 'day'), (2, 'week'), (3, 'month')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unit',
            field=models.IntegerField(choices=[(0, 'hour'), (1, 'day'), (2, 'week'), (3, 'month')]),
        ),
    ]
