# Generated by Django 3.2.9 on 2021-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20211105_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_reservering',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
