# Generated by Django 3.2.8 on 2021-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1)),
                ('tel', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=256)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
